apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8sss
images:
- name: ghcr.io/andsens/k8sss-bootstrap
  newTag: 0.2.1
- name: cr.step.sm/smallstep/step-ca
  newTag: 0.29.0
resources:
- namespace.yaml
- deployment.yaml
configMapGenerator:
- files:
  - setup.sh
  - admin.tpl
  - ca.json
generatorOptions:
  disableNameSuffixHash: true
