apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8sss
images:
- name: ghcr.io/andsens/k8sss-bootstrap
  newTag: 0.2.1
- name: cr.step.sm/smallstep/step-ca
  newTag: 0.29.0
resources:
- namespace.yaml
- k8sss.yaml
configMapGenerator:
- files: [setup-k8sss-config.sh]
  name: k8sss-scripts
- files: [admin.tpl]
  name: k8sss-templates
- files: [k8sss.json]
  name: k8sss-config
generatorOptions:
  disableNameSuffixHash: true
