---
apiVersion: v1
kind: Service
metadata:
  name: k8sss
  labels:
    app.kubernetes.io/name: k8sss
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: k8sss
  ports:
  - name: api
    port: 9000
    nodePort: 9000
    targetPort: api
