name: Release

on:
  push:
    tags: ['v*']

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  build-bootstrap:
    uses: ./.github/workflows/build-bootstrap.yaml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
  release:
    needs: [test]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Create GitHub release
    steps:
    - uses: orbit-online/upkg-release@v1
      with:
        paths: bin LICENSE README.md
